version: "3"
services: 
  specdiff_api: 
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - specdiff_database

  specdiff_database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_vol:/var/lib/mysql
    ports:
      - 33068:3306

volumes:
  mysql_vol: